# Project information
site_name: Henduino Library
site_description: Libraries for Henduino Board Projects with core of Atmel and Espressif. Eletronic, automotive and technology information.
site_author: Dede Hendriono
site_url: https://henduino.github.io/library/
copyright: 'Copyright &copy; 2018 - 2020 <a href="https://henduino.github.io/library/">Dede Hendriono</a>'

# Configuration
theme:
  name: null
#  language: 'en'
  custom_dir: 'material'
  language: 'id'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/favicon.ico'
  icon:
    logo: octicons/tools-24
  features:
    - tabs
    - instant
  static_templates:
    - 404.html


  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true


# Repository
# repo_name: 'Henduino Library'
# repo_url: 'https://github.com/henduino/library'

# Customization
extra:
  disqus: 'henduino'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/henduino'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/hendriono'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://linkedin.com/in/hendriono'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/hendriono'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  - markdown.extensions.meta
  - markdown.extensions.attr_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      # linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.tabbed
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Extra CSS & Javascript
extra_javascript:
  - assets/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - assets/stylesheets/404.css
  - assets/stylesheets/pinout.css

# Minify
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - minify:
      minify_html: true

# Navigation
nav:
  - Beranda: index.md
  - Tentang: tentang.md
  - Artikel:
    - 2019:
      - Senyum Sejenak: blog/2019/senyum-sejenak-a.md
      - Prinsip ATM Belajar: blog/2019/prinsip-atm-belajar.md
      - Internet Sumber Belajar: blog/2019/internet-sumber-belajar.md
    # - Extensions:
    #   - Admonition: blog/ext/admonition.md
    #   - Codehilite: blog/ext/codehilite.md
    #   - Footnotes: blog/ext/footnotes.md
    #   - Metadata: blog/ext/metadata.md
    #   - Permalink: blog/ext/permalinks.md
    #   - Pymdown: blog/ext/pymdown.md
  - IT:
    - Git:
      - Fungsi gitignore: it/gitignore.md
      - Hapus Jejak File: it/untrack-files.md
      - Menggunakan Submodule Git: it/submodule-git.md
    - Network:
      - Bit v.s. Byte: it/bit-vs-byte.md
      - Office Remote: it/office-remote.md
  - Elektronika:
    - Dasar:
      - Reference Designator: tnt/refdes.md
      - Baterai: tnt/baterai.md
      - Resistor: tnt/resistor.md
      - Breadboard: tnt/breadboard-prototyping.md
      - Memilih Arduino Uno: tnt/memilih-arduino.md
      - Install Arduino di MX Linux: tnt/install-arduino.md
      - ATiny85 Arduino IDE: tnt/attiny85-arduino.md
      - Driver Signature Enforcement: tnt/dse.md
      - Blue Pill Unknown Device: tnt/bluepill-unknown-device.md
      - The Untold History of Arduino: tnt/the-untold-history-of-arduino.md
    - Papan:
      - Mengenal Mikrokontroler: papan/mikrokontroler.md
      - Mengenal Arduino: papan/apa-itu-arduino.md
      - Mengenal Arduino Uno: papan/mengenal-arduino-uno.md
      - Mengenal Arduino Mega2560: papan/mengenal-arduino-mega2560.md
      - Mengenal Arduino Leonardo: papan/mengenal-arduino-leonardo.md
      - Mengenal Arduino Nano: papan/mengenal-arduino-nano.md
      - Mengenal Arduino Pro Mini: papan/mengenal-arduino-pro-mini.md
    - Sensor:
      - Accelerometer ADXL335: sensor/accelerometer-adxl335.md
  - Otomotif:
    - Alat:
      - Vernier Caliper: tools/vernier-caliper.md
      - Secure Key Shutter: tools/secure-key-shutter.md
    - Ototronik:
      - Pendahuluan: ototronik/pendahuluan-ototronik.md
      - Standar DIN 72552: ototronik/din-72552.md
      - Mengenal Sekring: ototronik/fuse.md
      - Mengenal OBD: ototronik/EOBD2-OBDII.md
      - OBD-II Pinout: ototronik/OBDII-Pinout.md
      - Kedipan MIL Honda PGM-FI: ototronik/mil-pgmfi.md
      - DLC Honda PGM-FI: ototronik/dlc-honda.md
      - Sensor Honda PGM-FI: ototronik/sensor-pgmfi.md
      - Parasit Penguras Arus: ototronik/parasit-baterai.md
      - Bersihkan Terminal Baterai: ototronik/bersihkan-terminal-baterai.md
      - Sistem Starter Sepeda Motor: ototronik/starter-sepeda-motor.md
      - Dwell Sistem Pengapian: ototronik/dwell.md
      - Menyetel Waktu Pengapian: ototronik/ignition-timing.md
      - Identifikasi Regulator Mekanik: ototronik/id-regulator-mekanik.md
      - Prinsip Regulator Mekanik: ototronik/prinsip-regulator-mekanik.md
      - Memeriksa Rectifier Alternator: ototronik/periksa-rectifier-alt.md
#      - Pulser dan Reluctor: ototronik/pulser-reluctor.md
    - Mesin:
      - Desmodromic: engine/desmodromic.md
      - Overhead Valve: engine/overhead-valve.md
      - Overhead Cam: engine/overhead-cam.md
      - Penyebab Overheating: engine/overheating-mesin.md
      - Memeriksa Tutup Radiator: engine/periksa-radiator-cap.md
      - Pehitungan Roda Gigi: engine/hitung-roda-gigi.md
      - Rasio Torsi dan Kecepatan: engine/grts-roda-gigi.md
    - Bank Soal:
      - PAT XI TBSM: soal/pat-xi-tbsm.md

# Google Analytics
google_analytics:
  - 'UA-9289123-14'
  - 'auto'