# Project information
site_name: Henduino Library
site_description: Libraries for Henduino Board Projects with core of Atmel and Espressif
site_author: Dede Hendriono
site_url: https://henduino.github.io/library/

<<<<<<< HEAD
# Repository
repo_name: henduino/library
repo_url: https://github.com/henduino/library
edit_uri: ""

=======
>>>>>>> gh-pages
# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Dede Hendriono'

# Configuration
theme:
  name: 'material'
<<<<<<< HEAD
  language: 'en'
=======
  custom_dir: 'theme'
  language: 'id'
>>>>>>> gh-pages
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
<<<<<<< HEAD

# Navigation
nav:
  - Home: index.md
  - About: about.md
=======
  favicon: 'img/favicon.ico'
  logo:
    icon: 'local_library'
  feature:
    tabs: true

# Repository
repo_name: 'Henduino Library'
repo_url: 'https://github.com/henduino/library'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  disqus: 'hendriono'
  social:
    - type: 'github'
      link: 'https://github.com/henduino'
    - type: 'twitter'
      link: 'https://twitter.com/hendriono'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/hendriono'
    - type: 'facebook'
      link: 'https://www.facebook.com/dede.hendriono'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extra CSS & Javascript
extra_css:
  - 'assets/stylesheets/scrollProgress.css'
extra_javascript:
  - 'assets/javascripts/scrollProgress.min.js'

# Navigation
nav:
    - Beranda: index.md
    - Tentang: tentang.md
    - Perpustakaan: 
      - Sensor:
        - Accelerometer ADXL335: library/sensor/accelerometer-adxl335.md
    - Blog:
      - 2019: 
        - Untrack Files: blog/2019/untrack-files.md
        - The Untold History of Arduino: blog/2019/the-untold-history-of-arduino.md
>>>>>>> gh-pages
