# Project information
site_name: Henduino Library
site_description: Libraries for Henduino Board Projects with core of Atmel and Espressif
site_author: Dede Hendriono
site_url: https://henduino.github.io/library/

# Repository
repo_name: henduino/library
repo_url: https://github.com/henduino/library
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Dede Hendriono'

# Configuration
theme:
  name: 'material'