# Project information
site_name: Henduino Library
site_description: Libraries for Henduino Board Projects with core of Atmel and Espressif
site_author: Dede Hendriono
site_url: https://henduino.github.io/library/

# Repository
# repo_name: henduino/library
# repo_url: https://github.com/henduino/library

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Dede Hendriono'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'theme'
  language: 'id'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/favicon.ico'
  logo:
    icon: 'local_library'
  feature:
    tabs: true

# Repository
repo_name: 'Henduino Library'
repo_url: 'https://github.com/henduino/library'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  disqus: 'henduino'
  social:
    - type: 'github'
      link: 'https://github.com/henduino'
    - type: 'twitter'
      link: 'https://twitter.com/hendriono'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/hendriono'
    - type: 'facebook'
      link: 'https://www.facebook.com/hendriono'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Google Analytics
google_analytics:
  - 'UA-9289123-14'
  - 'auto'

# Extra CSS & Javascript
extra_css:
  - 'assets/stylesheets/scrollProgress.css'
  - 'assets/stylesheets/pinout.css'
extra_javascript:
  - 'assets/javascripts/scrollProgress.min.js'

# Navigation
nav:
  - Beranda: index.md
  - Tentang: tentang.md
  - Otomotif:
    - Ototronik:
      - Pendahuluan: oto/tronik/pendahuluan-ototronik.md
      - Dwell Sistem Pengapian: oto/tronik/dwell.md
  - Papan:
    - Mengenal Mikrokontroler: papan/mikrokontroler.md
    - Mengenal Arduino: papan/apa-itu-arduino.md
    - Mengenal Arduino Uno: papan/mengenal-arduino-uno.md
    - Mengenal Arduino Leonardo: papan/mengenal-arduino-leonardo.md
    - Mengenal Arduino Nano: papan/mengenal-arduino-nano.md
  - Pustaka: 
    - Sensor:
      - Accelerometer ADXL335: library/sensor/accelerometer-adxl335.md
  - Blog:
    - 2019:
      - Internet Sumber Belajar: blog/2019/internet-sumber-belajar.md
      - Memilih Arduino Uno: blog/2019/memilih-arduino.md
      - The Untold History of Arduino: blog/2019/the-untold-history-of-arduino.md
      - Hapus Jejak File: blog/2019/untrack-files.md
      - Menggunakan Submodule Git: blog/2019/submodule-git.md
    - Extensions:
      - Admonition: blog/ext/admonition.md
      - Codehilite: blog/ext/codehilite.md
      - Footnotes: blog/ext/footnotes.md
      - Metadata: blog/ext/metadata.md
      - Permalink: blog/ext/permalinks.md
      - Pymdown: blog/ext/pymdown.md
